import assert from 'node:assert/strict'
import { describe, test } from 'node:test'

import {
  LATEST_RELEASE_API_URL,
  RELEASE_WORKFLOW_URL,
  UPDATE_REPOSITORY,
} from './update-source'

describe('update source', () => {
  test('uses the downstream repository release generated by its action', () => {
    assert.equal(UPDATE_REPOSITORY, 'MIEnchating/new-api')
    assert.equal(
      LATEST_RELEASE_API_URL,
      'https://api.github.com/repos/MIEnchating/new-api/releases/latest'
    )
    assert.equal(
      RELEASE_WORKFLOW_URL,
      'https://github.com/MIEnchating/new-api/actions/workflows/release.yml'
    )
  })
})
