/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/
import assert from 'node:assert/strict'

import { describe, test } from 'vitest'

import {
  LATEST_RELEASE_API_URL,
  RELEASE_WORKFLOW_URL,
  UPDATE_REPOSITORY,
} from './update-source'

describe('update source', () => {
  test('uses the downstream repository release generated by its action', () => {
    assert.equal(UPDATE_REPOSITORY, 'MIEnchating/new-api')
    assert.equal(
      LATEST_RELEASE_API_URL,
      'https://api.github.com/repos/MIEnchating/new-api/releases/latest'
    )
    assert.equal(
      RELEASE_WORKFLOW_URL,
      'https://github.com/MIEnchating/new-api/actions/workflows/release.yml'
    )
  })
})
